build_packages:
# As a general rule, binaries built on one Linux distro will only
# work on other Linux distros that are the same age or newer.
# Therefore, if we want to make binaries that run on most Linux distros,
# we have to use an old enough distro.

# Ubuntu
- label: ubuntu-18.04
  os: ubuntu-18.04
  package: deb
- label: ubuntu-20.04
  os: ubuntu-20.04
  package: deb
- label: ubuntu-22.04
  os: ubuntu-22.04
  package: deb

# Debian
- label: debian-10
  os: ubuntu-18.04
  package: deb
- label: debian-11
  os: ubuntu-20.04
  package: deb

# CentOS
- label: centos-7
  os: ubuntu-22.04
  image: kong/kong-build-tools:rpm-1.8.1
  package: rpm

# RHEL
- label: rhel-7
  os: ubuntu-22.04
  image: kong/kong-build-tools:rpm-1.8.1
  package: rpm
