name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          matrix_file=".github/matrix-full.yml"
          echo "matrix=$(yq -I=0 -o=json $matrix_file)" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
 
  job3:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix).b }}
    steps:
      - run: echo 1
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix2).b_p }}
    steps:
      - run: echo 2
