name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Kong source code
        uses: actions/checkout@v3
      - id: set-matrix
        run: |
          matrix_file=".github/matrix-full.yml"
          echo "matrix=$(yq -I=0 -o=json $matrix_file)" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

  build-image:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      uses: docker/build-push-action@v3
      # This can't be cached, pongo relies on org.opencontainers.image.revision label
      # which should be set to current commit's SHA. pongo uses this label to clone
      # kong-ee repo, checkout it and copy into the dev image.
      # If it there's a way to modify the label after image is built, or pongo has
      # a way to override it, then we can cache it. But this usually takes 30s, so
      # we should be fine-ish.
      with:
        file: Dockerfile
        context: .
        push: false
        tags: "test-cve:latest"

    - name: Scan AMD64 Image digest
      uses: Kong/public-shared-actions/security-actions/scan-docker-image@v1
      with:
        asset_prefix: kong-${{ github.sha }}-${{ matrix.label }}-linux-amd64
        image: test-cve:latest

    - name: Export Docker Image
      run: |
        mkdir docker-image
        docker image save -o docker-image/image.tar test-cve:latest

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: docker-image/**
        retention-days: 3

