name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Kong source code
        uses: actions/checkout@v3
      - id: set-matrix
        run: |
          matrix_file=".github/matrix-full.yml"
          echo "matrix=$(yq -I=0 -o=json $matrix_file)" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
 
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: a 
        run: |
          echo ${{ fromJSON(needs.job1.outputs.matrix) }}
          echo ">>>>>>"
          echo ${{ fromJSON(needs.job1.outputs.matrix).smoke_tests }}

  job3:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.job1.outputs.matrix).release-packages }}
    steps:
      - run: echo 1
